---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo12-kustomization-monitoringflux-git
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./monitoring/configs
  prune: false
  sourceRef:
    kind: GitRepository
    name: demo12-source-monitoring-git
