---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo12-kustomization-monitoring-git
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./monitoring/controllers/kube-prometheus-stack
  prune: false
  sourceRef:
    kind: GitRepository
    name: demo12-source-monitoring-git
