---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: demo6-source-helm
  namespace: flux-system
spec:
  interval: 1m0s
#  url: https://charts.bitnami.com/bitnami
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
