---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo7-kustomize-oci
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: demo7-source-oci
  targetNamespace: ocidemo-ns
